author: Miles Chen
markdown: redcarpet
encoding: utf-8

theme: jekyll-theme-cayman
title: Miles Space
description: Talk is cheap. Show me the code.
google_analytics: UA-11765858-7

gems:
- jekyll-sitemap
